# Generated by Django 3.1.1 on 2020-09-10 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('admin_user', models.ManyToManyField(related_name='admin_user', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ManyToManyField(related_name='project_manager', to=settings.AUTH_USER_MODEL)),
                ('team_member', models.ManyToManyField(related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
