# Generated by Django 3.1.1 on 2020-09-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20200911_0325'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='unique_membership'),
        ),
    ]
