# Generated by Django 3.1.1 on 2020-09-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20200911_0708'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('team_name',), name='unique_team_name'),
        ),
    ]
