# Generated by Django 3.1.1 on 2020-09-20 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeverityLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('assignee', models.ManyToManyField(blank=True, related_name='task_assignee', to=settings.AUTH_USER_MODEL)),
                ('priority_level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.prioritylevel')),
                ('severity_level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.severitylevel')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.stage')),
                ('task_creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task_creator', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
