# Generated by Django 3.1.1 on 2020-09-09 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('priority_level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.prioritylevel')),
                ('severity_level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.severitylevel')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tasks.stage')),
                ('task_creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='team_members.teammember')),
            ],
        ),
    ]
