# Generated by Django 3.1.1 on 2020-09-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_checklistitem_taskassignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
