# Generated by Django 3.1.1 on 2020-09-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_members', '0001_initial'),
        ('tasks', '0004_auto_20200909_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, related_name='task_assignee', to='team_members.TeamMember'),
        ),
        migrations.DeleteModel(
            name='TaskAssignee',
        ),
    ]
