# Generated by Django 3.1.1 on 2020-09-10 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0005_auto_20200909_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ManyToManyField(blank=True, related_name='task_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
