# Generated by Django 3.1.1 on 2020-09-10 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20200910_0228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team_members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admin_user',
            field=models.ManyToManyField(related_name='admin_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='project_manager',
            field=models.ManyToManyField(related_name='project_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='team_member',
            field=models.ManyToManyField(related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
