# Generated by Django 3.1.1 on 2020-09-14 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('service_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sales.service')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='teams.team')),
            ],
        ),
    ]
