# Generated by Django 3.1.1 on 2020-10-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20201004_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
